services:
app1:
build: ./app
environment:
- INSTANCE_ID=app1
ports:
- "3001:3000"
app2:
build: ./app
environment:
- INSTANCE_ID=app2
ports:
- "3002:3000"
app3:
build: ./app
environment:
- INSTANCE_ID=app3
ports:
- "3003:3000"


balancer:
build: ./balancer
ports:
- "8080:8080"
depends_on:
- app1
- app2
- app3